from collections import namedtuple

DataConfigs = namedtuple('DataConfigs', 
                          ['source_path', 
                           'model_path',
                           'images_dir',
                           'if_white_background',
                           'if_eval',
                           'resolution_scale_factor',
                           'data_device'])

dcs = DataConfigs(source_path="opacoxel/data",
                  model_path="opacoxel/data/output",
                  images_dir="images",
                  if_white_background=False,
                  if_eval=False,
                  resolution_scale_factor=-1,
                  data_device="cuda")

OptimizationConfigs = namedtuple('OptimizationConfigs',
                                 ['iterations',
                                  'sh_degree',
                                  'position_lr_init',
                                  'position_lr_final',
                                  'position_lr_delay_mult',
                                  'position_lr_max_steps',
                                  'feature_lr',
                                  'opacity_lr',
                                  'scaling_lr',
                                  'rotation_lr',
                                  'percent_dense',
                                  'lambda_dssim',
                                  'densify_from_iter',
                                  'densify_until_iter',
                                  'densify_grad_threshold',
                                  'densification_interval',
                                  'opacity_reset_interval'])

ocs = OptimizationConfigs(iterations=30_000,
                          sh_degree=3,
                          position_lr_init=0.00016,
                          position_lr_final=0.0000016,
                          position_lr_delay_mult=0.01,
                          position_lr_max_steps=30_000,
                          feature_lr=0.0025,
                          opacity_lr=0.05,
                          scaling_lr=0.005,
                          rotation_lr=0.001,
                          percent_dense=0.01,
                          lambda_dssim=0.2,
                          densify_from_iter=500,
                          densify_until_iter=15_000,
                          densify_grad_threshold=0.0002,
                          densification_interval=100,
                          opacity_reset_interval=3000)